### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SylisMC** [AthionOfficial/Mods#3]
better sprinting (forge) - handy. has fly boost for creative mode. usually up to date,
https://minecraft.curseforge.com/projects/better-sprinting

Macro keybinds (light loader) Super handy to use with repetative commands. like /wand, copy, tpaccept paste rotate brush mask etc
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1275039-macro-keybind-mod-1-11-2-version-available

voxelmap (light loader) possibly a better mini map. comes with build in waypoints. tp to waypoints. a wold map of all explored content. share cords on the Wmap with anyone on the server. tp to any location on the wmap with a right click option. 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2261180-voxelmap-1-11-2-1-10-1-9-4-1-8-9-1-7-10-1-6-4-a

**Comment by dordsor21** [comment]
Done
